// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsEj2LcmV_N73aoTLLrr1wWrUXY38_5EE',
    appId: '1:406508716506:web:f0e536dd9b79b07bbf00e3',
    messagingSenderId: '406508716506',
    projectId: 'smart-queue-app-b0d5a',
    authDomain: 'smart-queue-app-b0d5a.firebaseapp.com',
    storageBucket: 'smart-queue-app-b0d5a.firebasestorage.app',
    measurementId: 'G-FKXE1EGFD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSqv2yGG_UPD4fbgVuWGmCS1EmPgCk-iI',
    appId: '1:406508716506:android:4b64c2c51eed59a6bf00e3',
    messagingSenderId: '406508716506',
    projectId: 'smart-queue-app-b0d5a',
    storageBucket: 'smart-queue-app-b0d5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGm4JUGlqTO7dUq8HQloCU8rRwIzQvzCM',
    appId: '1:406508716506:ios:a616610fd684a691bf00e3',
    messagingSenderId: '406508716506',
    projectId: 'smart-queue-app-b0d5a',
    storageBucket: 'smart-queue-app-b0d5a.firebasestorage.app',
    iosBundleId: 'com.example.flutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGm4JUGlqTO7dUq8HQloCU8rRwIzQvzCM',
    appId: '1:406508716506:ios:a616610fd684a691bf00e3',
    messagingSenderId: '406508716506',
    projectId: 'smart-queue-app-b0d5a',
    storageBucket: 'smart-queue-app-b0d5a.firebasestorage.app',
    iosBundleId: 'com.example.flutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsEj2LcmV_N73aoTLLrr1wWrUXY38_5EE',
    appId: '1:406508716506:web:b375f1e8fdc5c2ffbf00e3',
    messagingSenderId: '406508716506',
    projectId: 'smart-queue-app-b0d5a',
    authDomain: 'smart-queue-app-b0d5a.firebaseapp.com',
    storageBucket: 'smart-queue-app-b0d5a.firebasestorage.app',
    measurementId: 'G-05Z5TW3GR4',
  );
}
